version: '3.8'

services:
  # DynamoDB Local for AWS services simulation
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: sloth-util-dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - sloth-util-network

  # LocalStack for AWS services simulation (optional)
  localstack:
    image: localstack/localstack:latest
    container_name: sloth-util-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,iam,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
    networks:
      - sloth-util-network

  # Miniflare for local Cloudflare Workers/D1/KV simulation (optional)
  miniflare:
    image: node:18-alpine
    container_name: sloth-util-miniflare
    working_dir: /app
    command: sh -c "npm install -g miniflare@3 && miniflare --kv QUOTES --d1 DB"
    ports:
      - "8787:8787"
    volumes:
      - miniflare_data:/app/data
    networks:
      - sloth-util-network

volumes:
  localstack_data:
  miniflare_data:

networks:
  sloth-util-network:
    driver: bridge
